version: '3'
services:
  mypostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: users_db
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  user-management-service:
    container_name: user-management-service
    image: user-management-service
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mypostgres
      - redis
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/users_db
networks:
  mynetwork:
    driver: bridge