apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  ports:
  - port: 8081 #port for user-management-service
    protocol: TCP
    name: http
  selector:
    app:  user-management-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
spec:
  selector:
    matchLabels:
      app:  user-management-service
  replicas: 1
  template:
    metadata:
      labels:
        app:  user-management-service
    spec:
      containers:
      - image: dasha12678/user-management-service:latest
        name: user-management-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8081 #port for user-management-service 
        env:
        - name: DB_HOST
          value: "jdbc:postgresql://${DB_HOST}"
        - name: DB_USER
          value: "${DB_USER}"
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"   
        - name: REDIS_HOST
          value: "${REDIS_HOST}"
        - name: REDIS_PORT
          value: "${REDIS_PORT}"
      restartPolicy: Always
