apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  ports:
  - port: 8081 #port for user-management-service
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
spec:
  selector:
    matchLabels:
      io.kompose.service: user-management-service
  replicas: 1
  template:
    spec:
      containers:
      - image: user-management-service
        name: user-management-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8081 #port for user-management-service
      restartPolicy: Always