name: Build, Test and Push
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
env:
  IMAGE_NAME: user-management-service
  # REPO_NAME: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-code
      uses: actions/checkout@v2
    - name: Build docker image
      run: |
        docker build . -t $IMAGE_NAME
    - name: Run docker container
      run: |
        docker run -d -e 8081:8081 -host=172.17.0.2 $IMAGE_NAME:latest && \
          docker ps && sleep 5
